apiVersion: v1
kind: Service
metadata: 
  name: gowebapp
  labels:
    run: gowebapp
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    run: gowebapp
    tier: frontend
